### ISSUE TITLE
Jitpack release 3.0.0 is missing .aar and .jar files

### ISSUE THREAD

**Issue by astarivi** [WrichikBasu/AudioFocusController#16]
Jitpack release 3.0.0 isn't building correctly. The only files that result from the build are the .pom archives.

![image](https://github.com/WrichikBasu/AudioFocusController/assets/111199883/c2ce0ec1-ac3f-4e60-81e6-c89b89ff29cb)

This happens with commit 316c8eb75c4d7035e9da4b8457b8226076a2e46c as target, too

**Comment by WrichikBasu** [comment]
Yeah, I encountered it a while back. Use release `v2.1` for now. I am investigating.

**Comment by WrichikBasu** [comment]
@astarivi Please try with release 3.0.1 and let me know.

**Comment by WrichikBasu** [comment]
Resolved in release 3.0.1.

Thanks for bringing it up, and for your interest in the library.

**Comment by astarivi** [comment]
It's all working now, thank you!
