### ISSUE TITLE
Add license metadata to publication POM

### ISSUE THREAD

**Issue by astarivi** [WrichikBasu/AudioFocusController#18]
Due to #8, adding the license information to apps using this library is more important than ever. To aid (or outright automate) this process, the license metadata could be added to the POM file for publications to Jitpack, or other repositories. This way, the license (or to be precise, a link to it) would be bundled with every copy of the library.

If adequate, I could PR the required changes to the build.gradle file to make this behaviour possible.

**Comment by WrichikBasu** [comment]
Feel free to submit a PR. Improvements are always welcome.
